name: ZhiYi-W    #你的 github.com 上的 GitHub Action 的名称

on: [ pull_request, workflow_dispatch ]           #何时执行你的 GitHub Action，'pull_request' -> 在每次合并（拉取）请求，'workflow_dispatch' -> 允许通过 github.com 手动执行

env:                                              #环境变量，后续可以使用 ${{ env.MINECRAFT_VERSION }} 引用，可以用作重复的信息并允许后续模组新的更新中快速更改
  MINECRAFT_VERSION: 1.21
  JAVA_VERSION: 21
  VERSION: 1.1.0+1.21
  RELEASE_NAME: 一款常用生存指令模组 1.1.0
#  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:                                             #在这里你就会实际告诉 GitHub 的服务器需要做什么
  build:                                          #要发布你的模组，你只需要一个 job，这里称为 build。
    runs-on: ubuntu-latest                        #'runs-on' 指定了操作系统（linux）。
    steps:                                        #在 'steps' 中你会列举出所有单独的命令，例如 Kir-Antipov 的 MC-Publish。
      - name: 检查环境变量
        run: env

      - name: 签出存储库
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 设置 Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: 使 Gradle Wrapper 可执行
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: 构建
        run: ./gradlew clean build
               - name: 发布（CurseForge/Modrinth/Github）
               uses: Kir-Antipov/mc-publish@v3.2
               with:
                 curseforge-id: ZhiYi
                 curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

#                 modrinth-id: 1q2w3e4r
#                 modrinth-token: "${{env.MODRINTH_TOKEN}}"

                 github-tag: "v${{env.VERSION}}"
                 github-token: "${{env.GITHUB_TOKEN}}"

                 name: "${{env.RELEASE_NAME}}"
                 version: "${{env.VERSION}}"
                 version-type: release
                 changelog-file: CHANGELOG.md

                 loaders: fabric
                 game-versions: "${{env.MINECRAFT_VERSION}}"
                 java: "${{env.JAVA_VERSION}}"